var baseDir = "@@@1";
var flaName = "@@@2";
var jsonName = "@@@3";
var fileURI = FLfile.platformPathToURI(baseDir + flaName);
var jsonURI = FLfile.platformPathToURI(baseDir + jsonName);
var doc = fl.openDocument(fileURI);
doc.sourcePath = "../src";
doc.docClass = "com.crazyfm.extensions.flashPhysicsEditor.FlashPhysicsJSONBuilder";
doc.libraryPath = "../../../crazyfm/dependencies/crazyfm/";
doc.testMovie();
fl.outputPanel.save(jsonURI);
fl.closeDocument(doc, false);
//fl.quit(false);